apiVersion: v1
kind: Service
metadata:
  name: user-service
spec:
  selector:
    app: user-service
  ports:
    - protocol: TCP
      port: 80 # Service port
      targetPort: 3001 # Container port
      nodePort: 30001 # Expose on a different NodePort than payment-service
  type: NodePort
